### ISSUE TITLE
有个小问题咨询下

### ISSUE THREAD

**Issue by redtecher** [kb1000fx/hexo-theme-meadow#1]
首先感谢编写这个主题，已经安装上，很喜欢。
有个问题想咨询下
黑夜模式下超链接的蓝色有点深了，想调淡一点，请问在哪个地方修改。

**Comment by kb1000fx** [comment]
请问是具体哪个地方的超链接，最好能附个图片，我这里没有发现这种情况。
去掉所有超链接的颜色可以在~hexo/themes/meadow/source/css文件夹中的main.styl文件中加入
```
a{
  color: unset !important;
  &:visited, &:link {
      color: unset !important;
  }
}
```
其中unset可以替换成你想要的颜色，设为unset颜色会和普通文字一样

**Comment by kb1000fx** [comment]
![QQ截图20200226210325](https://user-images.githubusercontent.com/28474026/75347960-e10d0e00-58dc-11ea-9106-3ec510001bd0.png)
上面的方法会修改所有超链接的颜色，如果是只想改文章内的超链接颜色，就像图里的这样，可以把上面的内容改成
```
#article a{
  color: unset !important;
  &:visited, &:link {
      color: unset !important;
  }
}
```

**Comment by redtecher** [comment]
OK，非常感谢！
