### ISSUE TITLE
如何设置标题图片？

### ISSUE THREAD

**Issue by Chao-zhi** [kb1000fx/hexo-theme-meadow#13]
我注意到您自己的博客有些文章的标题上有显示背景图片，但是我在文档中没有找到如何使用标题图片。可否在文档中添加这部分的内容，以方便我们学习使用。

**Comment by kb1000fx** [comment]
在Front-matter里添加image参数，内容就是图片的路径(网站根目录下的绝对路径，不是相对于md文件的路径，编译后source文件夹下内容会直接放在根目录下)

关于Front-matter详情参见https://hexo.io/zh-cn/docs/front-matter
