### ISSUE TITLE
想问一下

### ISSUE THREAD

**Issue by Fukelibie** [kb1000fx/hexo-theme-meadow#5]
我在文章代码界面用markdown写的[文字](网址)，但是出来的就是[文字](网址)，而不是以文字为名的网址...想问一下这种情况怎么办？
以及感谢你上次的回复！

**Comment by kb1000fx** [comment]
没太看懂问题的描述，如果是想插入超链接的话需要使用 [描述文字](URL) 这样的格式，例如
```markdown
[百度](https://www.baidu.com/)
```
显示的结果是：[百度](https://www.baidu.com/)

如果不是这个问题的话请附个详细点的图

**Comment by Fukelibie** [comment]
哦我找到了问题。
我写的是< center>[百度](www.baidu.com)< /center>
出来的时候就是[百度](www.baidu.com)而不是百度。
所以它是不可以居中的吗？
还有想问下评论怎么搭建呢？看了你的ducument，把来比力的data_uid贴到对应的livere_data_uid处，然后运行后没见到评论区。
想问下我还需要做什么操作吗？
感谢 : )

**Comment by Fukelibie** [comment]
出来的时候是[百度] （www.baidu.com），之前的回复它蓝了。。。

**Comment by kb1000fx** [comment]
center标签已经废弃，对于需要居中的文字可以下面的方式：
```html
<div style="text-align:center;"> 要居中的文字 </div>
```
由于html标签内的内容不会被markdown解析，如果要居中的内容里有链接，就不能写成`[XX](URL)`的形式，需要写成
```html
<a href="https://www.baidu.com/">百度</a>
```
所以如果是想居中一个链接，最后就是这种
```HTML
<div style="text-align:center;">
    <a href="https://www.baidu.com/">百度</a>
</div>
```

来比利评论的话我猜你可能是没有把comment下第一个use里的false改成livere
