### ISSUE TITLE
自动生成的摘要预览异常

### ISSUE THREAD

**Issue by camus0129** [kb1000fx/hexo-theme-meadow#6]
在自动生成的摘要中，包含代码的情况下，则包含的代码超过一行的情况下，此时摘要的预览显示异常

**Comment by kb1000fx** [comment]
当摘要里包含部分代码框或超链接时会出现这种状况 (包含完整代码框时则不会出现问题)，可以使用`<!--more-->`标记来手动控制摘要长度

**Comment by camus0129** [comment]
> 
> 
> 当摘要里包含部分代码框或超链接时会出现这种状况 (包含完整代码框时则不会出现问题)，可以使用`<!--more-->`标记来手动控制摘要长度

感谢，这个方法确实有用

不知道这个问题是否能彻底解决呢？这样也方便后面的人，避免出现同样的问题

**Comment by kb1000fx** [comment]
@camus0129 已解决，请更新主题
