### ISSUE TITLE
可以多加一些图标吗？

### ISSUE THREAD

**Issue by gxres042** [kb1000fx/hexo-theme-meadow#7]
目前我看了一下作者做的平台图标，发现例如B站的一些平台图标都没有；
同时，我没有发现主题有对应的 RSS 位置，所以我在平台那个位置放一个 RSS 链接，但是刚好没有 RSS 的图标
请作者加一些中国大陆平台的图标（可以像网易云之类的），顺便也加一个 RSS 图标上去，谢谢（

**Comment by kb1000fx** [comment]
b站，网易云，rss除了这三个还有其他需要的吗，没有就先加这三个了

**Comment by gxres042** [comment]
> b站，网易云，rss除了这三个还有其他需要的吗，没有就先加这三个了

目前来说只需要这三个，谢谢作者了。
