### ISSUE TITLE
友情链接BUG

### ISSUE THREAD

**Issue by gxres042** [kb1000fx/hexo-theme-meadow#8]
麻烦作者了，我发现了一个新的问题
我刚刚在电脑预览我的友情链接（就是左侧“关于”那个），它只能显示三个并不能向下滚动
希望作者修复该问题之后通知我更新主题，谢谢（

**Comment by kb1000fx** [comment]
已修复下列问题，请更新主题

#7  
+ 新增三个图标，图标名称用法参见 https://garybear.cn/hexo-theme-meadow/doc/icon/index.html

#8  
+ 在侧边栏添加了一个隐藏的滚动条(看不见，但是可以动)
+ 目前默认是将滚动条放在了内侧，仅友链区域可滚动
+ 如果需要整个侧边栏一起滚，我在css里做了注释，根据注释删掉两行即可将滚动条外置

**Comment by gxres042** [comment]
好的 谢谢

**Comment by gxres042** [comment]
但是我测试了一下，侧边栏的滚动条仍然不显示，并且很难看到更下面的友链

**Comment by gxres042** [comment]
目前我有18个友链，但是滚动只能显示14个，如果滚动条外置的话只能显示个位数

**Comment by kb1000fx** [comment]
问题出现在第82行
```
max-height: calc(100vh - 414px);
```
+ 如果滚动条外置的话，除了我注释的两个地方还要把这一行去掉
+ 如果内置的话，参考自己的布局 (出现问题的原因应该是咱俩简介和社交贴纸行数不一样) 把这一行的414调整成合适的数值

**Comment by gxres042** [comment]
> 问题出现在第82行
> 
> ```
> max-height: calc(100vh - 414px);
> ```
> 
> * 如果滚动条外置的话，除了我注释的两个地方还要把这一行去掉
> * 如果内置的话，参考自己的布局 (出现问题的原因应该是咱俩简介和社交贴纸行数不一样) 把这一行的414调整成合适的数值

调成600px就能全部加载我的18个友链了（
感谢作者的耐心，我的Issues至此完毕
