### ISSUE TITLE
中文版的主题

### ISSUE THREAD

**Issue by Halobin** [kb1000fx/hexo-theme-meadow#9]
请问有中文版的主题吗?

**Comment by kb1000fx** [comment]
主题中包含了中英两种语言，将hexo目录下的`_config.yml`文件中的language一行设为zh-CN就能切换到中文

**Comment by Halobin** [comment]
可以加一个leetcode的图标吗

**Comment by kb1000fx** [comment]
> 可以加一个leetcode的图标吗

已更新

**Comment by Halobin** [comment]
请问一下啊 怎么更改主界面的图片啊

**Comment by kb1000fx** [comment]
> 请问一下啊 怎么更改主界面的图片啊

主界面图片是哪个，能附个图吗

**Comment by Halobin** [comment]
![QQ图片20200829163830](https://user-images.githubusercontent.com/51705877/91632875-7d43d900-ea16-11ea-9dd9-60d2c479ea8a.png)

**Comment by Halobin** [comment]
> > 请问一下啊怎么更改主界面的图片啊
> 
> 主界面图片是其中，能附个图吗

请问下面发的这个图 如何更改

**Comment by kb1000fx** [comment]
> 请问下面发的这个图 如何更改

主题配置文件的第一行avatar，改成图片路径就行

**Comment by Halobin** [comment]
我改完图片裂开了

**Comment by Halobin** [comment]
刚刚那个leetcode图标，我本地可以应用，传到github打开就显示不了了

**Comment by kb1000fx** [comment]
> 刚刚那个leetcode图标，我本地可以应用，传到github打开就显示不了了

你博客里的leetcode图标我看是正常的，至于头像应该是你图标路径写错了

**Comment by Halobin** [comment]
请问图片要存在哪个文件夹

**Comment by kb1000fx** [comment]
> 请问图片要存在哪个文件夹

随便找个地方放着就行，avatar下填上对应的路径就可以。
hexo下source文件夹下的内容在编译后会直接位于根目录，我是在source下建了个images文件夹存放头像以及文章内的图片，相应的我在avatar一行写的就是`/images/avatar.webp`

**Comment by Halobin** [comment]
可以了，谢谢你了。

**Comment by kb1000fx** [comment]
帮我点个star可以吗

**Comment by Halobin** [comment]
好的

**Comment by Halobin** [comment]
请问 搜索功能怎么样 我在你博客上好像都搜索不了

**Comment by Halobin** [comment]
> 帮我点个star可以吗

朋友 为什么代码块不会左对齐呀

**Comment by kb1000fx** [comment]
> 请问 搜索功能怎么样 我在你博客上好像都搜索不了

搜索和代码块异常居中问题已修复，搜索功能的使用参见[本地搜索](https://garybear.cn/hexo-theme-meadow/doc/#/zh-CN/%E6%8F%92%E4%BB%B6/%E6%9C%AC%E5%9C%B0%E6%90%9C%E7%B4%A2)

**Comment by Halobin** [comment]
> > 请问 搜索功能怎么样 我在你博客上好像都搜索不了
> 
> 搜索和代码块异常居中问题已修复，搜索功能的使用参见[本地搜索](https://garybear.cn/hexo-theme-meadow/doc/#/zh-CN/%E6%8F%92%E4%BB%B6/%E6%9C%AC%E5%9C%B0%E6%90%9C%E7%B4%A2)

好的 谢谢

**Comment by Halobin** [comment]
请问博客中 这句 “人间五十年，岂有长生不灭者？”是怎么加上的。

**Comment by kb1000fx** [comment]
> 请问博客中 这句 “人间五十年，岂有长生不灭者？”是怎么加上的。

修改hexo根目录下config.yml文件中description一行

**Comment by Halobin** [comment]
> > 请问博客中 这句 “人间五十年，岂有长生不灭者？”是怎么加上的。
> 
> 修改hexo根目录下config.yml文件中description一行

感谢

**Comment by Halobin** [comment]
问一下，文字中下标怎么会变成删除线了呢

**Comment by kb1000fx** [comment]
> 问一下，文字中下标怎么会变成删除线了呢

请发一下详细的截图，我试了一下使用`XXX<sub>yyy</sub>`标签这种形式没遇到所述问题，效果：

XXX<sub>yyy</sub>

**Comment by Halobin** [comment]
![image](https://user-images.githubusercontent.com/51705877/101229416-1865e200-36db-11eb-8dbc-39b8a12d97f0.png)
问一下 为什么会出现这种情况

**Comment by kb1000fx** [comment]
> 问一下 为什么会出现这种情况

我这没遇到这个问题，你试一下重新装一下主题吧
